### ISSUE TITLE
Is bindplane-agent managed/supervisor designed to only work with Binadplane OP Server?

### ISSUE THREAD

**Issue by shaiajneh** [observIQ/bindplane-agent#1916]
Hey There,
I am trying to use the bindplane agent with the OpAMP server available in [opamp-go](https://github.com/open-telemetry/opamp-go) repo. 

`manager.yaml`
```yaml
endpoint: "wss://127.0.0.1:4320/v1/opamp"
agent_id: 01JA80SGPG9EDY287MB3XH9ZBX
tls_config:
  insecure_skip_verify: true
```

`supervisor.yaml`
```yaml
server:
  endpoint: "ws://127.0.0.1:4320/v1/opamp"
  headers:
  tls:
    insecure: true
    insecure_skip_verify: true
capabilities:
  accepts_remote_config: true
  reports_remote_config: true
agent:
  executable: "/opt/observiq-otel-collector/observiq-otel-collector"
  description:
    non_identifying_attributes:
storage:
  directory: "/opt/observiq-otel-collector/supervisor_storage"
```

I can find the agent on the OpAMP Server, but when changing any of the configuration I get a not supported config error.

```
{"level":"info","ts":"2024-10-15T15:09:27.470+0300","caller":"collector/main.go:95","msg":"Starting In Managed Mode"}
{"level":"info","ts":"2024-10-15T15:09:27.472+0300","caller":"service/managed.go:79","msg":"Starting in managed mode"}
{"level":"info","ts":"2024-10-15T15:09:27.473+0300","caller":"service@v0.111.0/service.go:136","msg":"Setting up own telemetry..."}
{"level":"info","ts":"2024-10-15T15:09:27.473+0300","caller":"service@v0.111.0/service.go:185","msg":"Skipped telemetry setup."}
{"level":"info","ts":"2024-10-15T15:09:27.474+0300","caller":"service@v0.111.0/service.go:208","msg":"Starting /opt/observiq-otel-collector/observiq-otel-collector...","Version":"v1.61.1","NumCPU":12}
{"level":"info","ts":"2024-10-15T15:09:27.474+0300","caller":"extensions/extensions.go:39","msg":"Starting extensions..."}
{"level":"info","ts":"2024-10-15T15:09:27.474+0300","caller":"service@v0.111.0/service.go:234","msg":"Everything is ready. Begin running and processing data."}
{"level":"info","ts":"2024-10-15T15:09:27.738+0300","logger":"opamp","caller":"observiq/observiq_client.go:282","msg":"Successfully connected to server"}
{"level":"warn","ts":"2024-10-15T15:09:27.739+0300","logger":"config manager","caller":"observiq/agent_config_manager.go:114","msg":"Not supported config received skipping","config":""}
{"level":"info","ts":"2024-10-15T15:09:27.739+0300","logger":"opamp","caller":"observiq/observiq_client.go:349","msg":"Server does not support custom message measurements, stopping sender."}
{"level":"warn","ts":"2024-10-15T15:11:22.970+0300","logger":"config manager","caller":"observiq/agent_config_manager.go:114","msg":"Not supported config received skipping","config":""}
```
Is the supervisor only supported with ObserveIQ server?
